services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=app
      - CORS_ALLOW_ORIGINS=*
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data: